language: python
python:
  - "3.6"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8
  - pip install pytest
  - pip install -e .
script  :
  - flake8 -v --statistics -ignore=E402,F401
  - pytest -v
